name: Install Project
description: Install the Python, Poetry, and the project.
inputs:
  python-version: { default: "3.8", description: "Python Version" }
  poetry-version: { default: "1.8.1", description: "Poetry Version" }
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ inputs.poetry-version }}
    - name: Install Project
      run: poetry install --all-extras
      shell: bash