name: Build sonar reports
on: workflow_dispatch
# Uncomment the following lines to include this workflow in the CI on push
#on:
#  push:
#    branches:
#      - "**"
jobs:
  report:
    runs-on: decathlon
    env: # TO BE DEFINED
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Project
        uses: ./.github/actions/install-project
      - name: Make Reports
        run: echo reporters # TODO: Add reporters
      - name: Deploy Reports
        uses: SonarSource/sonarcloud-github-action@master